from core.logger import Logger
from llm.prompts import SYSTEM_PROMPT
from locators.locator_definition import LocatorDefinition


class LocatorGenerator:
    SUPPORTED_STRATEGIES = {
        "role",
        "label",
        "placeholder",
        "text",
        "test_id",
        "alt_text",
        "css",
        "xpath",
    }

    def __init__(self, llm):
        self.llm = llm
        self.log = Logger.get_logger(self.__class__.__name__)

    # ==========================================================
    # GENERATE
    # ==========================================================

    def generate(self, prompt: str) -> LocatorDefinition:
        if not prompt:
            raise ValueError("Locator generation prompt cannot be empty")

        self.log.info(
            f"[LOCATOR-GENERATOR] Generating locator | prompt_length={len(prompt)}"
        )

        try:
            result = self.llm.chat(
                user_prompt=prompt,
                system_prompt=SYSTEM_PROMPT,
                response_as_json=True,
            )

            self.log.info("[LOCATOR-GENERATOR] LLM response received")

            if not isinstance(result, dict):
                raise ValueError(
                    f"Invalid LLM response type: {type(result).__name__}"
                )

            strategy = result.get("strategy")
            value = result.get("value")
            options = result.get("options", {})

            # --------------------------------------------------
            # Strategy
            # --------------------------------------------------

            if not strategy:
                raise ValueError("LLM response does not contain 'strategy'")

            strategy = strategy.lower().strip()

            if strategy not in self.SUPPORTED_STRATEGIES:
                raise ValueError(
                    f"Unsupported locator strategy generated by LLM: {strategy}"
                )

            # --------------------------------------------------
            # Value
            # --------------------------------------------------

            if not value:
                raise ValueError("LLM response does not contain 'value'")

            if not isinstance(value, str):
                raise ValueError("Locator 'value' must be a string")

            # --------------------------------------------------
            # Options
            # --------------------------------------------------

            if options is None:
                options = {}

            if not isinstance(options, dict):
                raise ValueError("Locator 'options' must be an object")

            # --------------------------------------------------
            # Create definition
            # --------------------------------------------------

            definition = LocatorDefinition(
                strategy=strategy,
                value=value,
                options=options,
            )

            self.log.info(f"[LOCATOR-GENERATOR] Generated → strategy={strategy}")
            self.log.debug(
                f"[LOCATOR-GENERATOR] value={value} | options={options}"
            )

            return definition

        except Exception as error:
            self.log.error(f"[LOCATOR-GENERATOR] Generation failed → {error}")
            raise
